# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\dylan\Google Drive\Project Boxes\MSGC Project Box\Ground Station System\Antenna Tracker QtGui V4\trackermain.ui'
#
# Created: Sat May 14 11:16:13 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 690)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.incomingLabel = QtGui.QLabel(self.centralwidget)
        self.incomingLabel.setGeometry(QtCore.QRect(10, 20, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.incomingLabel.setFont(font)
        self.incomingLabel.setObjectName("incomingLabel")
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(260, 10, 21, 631))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.incomingData = QtGui.QTableWidget(self.centralwidget)
        self.incomingData.setGeometry(QtCore.QRect(20, 40, 221, 271))
        self.incomingData.setAutoScroll(False)
        self.incomingData.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.incomingData.setTabKeyNavigation(False)
        self.incomingData.setObjectName("incomingData")
        self.incomingData.setColumnCount(1)
        self.incomingData.setRowCount(8)
        item = QtGui.QTableWidgetItem()
        self.incomingData.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.incomingData.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.incomingData.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.incomingData.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.incomingData.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.incomingData.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.incomingData.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.incomingData.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.incomingData.setHorizontalHeaderItem(0, item)
        self.groundData = QtGui.QTableWidget(self.centralwidget)
        self.groundData.setGeometry(QtCore.QRect(10, 360, 251, 271))
        self.groundData.setAutoScroll(False)
        self.groundData.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.groundData.setTabKeyNavigation(False)
        self.groundData.setObjectName("groundData")
        self.groundData.setColumnCount(1)
        self.groundData.setRowCount(8)
        item = QtGui.QTableWidgetItem()
        self.groundData.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.groundData.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.groundData.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.groundData.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.groundData.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.groundData.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.groundData.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.groundData.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.groundData.setHorizontalHeaderItem(0, item)
        self.groundLabel = QtGui.QLabel(self.centralwidget)
        self.groundLabel.setGeometry(QtCore.QRect(20, 340, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.groundLabel.setFont(font)
        self.groundLabel.setObjectName("groundLabel")
        self.tabs = QtGui.QTabWidget(self.centralwidget)
        self.tabs.setEnabled(True)
        self.tabs.setGeometry(QtCore.QRect(280, 0, 931, 601))
        self.tabs.setAutoFillBackground(True)
        self.tabs.setTabPosition(QtGui.QTabWidget.West)
        self.tabs.setObjectName("tabs")
        self.Settings = QtGui.QWidget()
        self.Settings.setObjectName("Settings")
        self.bearingFrame = QtGui.QFrame(self.Settings)
        self.bearingFrame.setGeometry(QtCore.QRect(30, 30, 391, 261))
        self.bearingFrame.setFrameShape(QtGui.QFrame.WinPanel)
        self.bearingFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.bearingFrame.setObjectName("bearingFrame")
        self.gridLayoutWidget = QtGui.QWidget(self.bearingFrame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 30, 131, 211))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.bearingGrid = QtGui.QGridLayout(self.gridLayoutWidget)
        self.bearingGrid.setContentsMargins(0, 0, 0, 0)
        self.bearingGrid.setObjectName("bearingGrid")
        self.getLocal = QtGui.QRadioButton(self.gridLayoutWidget)
        self.getLocal.setChecked(True)
        self.getLocal.setObjectName("getLocal")
        self.bearingGrid.addWidget(self.getLocal, 0, 0, 1, 1)
        self.bearingSouth = QtGui.QRadioButton(self.gridLayoutWidget)
        self.bearingSouth.setObjectName("bearingSouth")
        self.bearingGrid.addWidget(self.bearingSouth, 3, 0, 1, 1)
        self.bearingEast = QtGui.QRadioButton(self.gridLayoutWidget)
        self.bearingEast.setObjectName("bearingEast")
        self.bearingGrid.addWidget(self.bearingEast, 2, 0, 1, 1)
        self.bearingWest = QtGui.QRadioButton(self.gridLayoutWidget)
        self.bearingWest.setObjectName("bearingWest")
        self.bearingGrid.addWidget(self.bearingWest, 4, 0, 1, 1)
        self.bearingNorth = QtGui.QRadioButton(self.gridLayoutWidget)
        self.bearingNorth.setObjectName("bearingNorth")
        self.bearingGrid.addWidget(self.bearingNorth, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.bearingFrame)
        self.label.setGeometry(QtCore.QRect(10, 10, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.manualAlt = QtGui.QLineEdit(self.bearingFrame)
        self.manualAlt.setGeometry(QtCore.QRect(230, 180, 113, 20))
        self.manualAlt.setText("")
        self.manualAlt.setObjectName("manualAlt")
        self.manualAltLabel = QtGui.QLabel(self.bearingFrame)
        self.manualAltLabel.setGeometry(QtCore.QRect(190, 160, 61, 16))
        font = QtGui.QFont()
        font.setItalic(True)
        self.manualAltLabel.setFont(font)
        self.manualAltLabel.setObjectName("manualAltLabel")
        self.manualLon = QtGui.QLineEdit(self.bearingFrame)
        self.manualLon.setGeometry(QtCore.QRect(230, 120, 113, 20))
        self.manualLon.setText("")
        self.manualLon.setObjectName("manualLon")
        self.manualLonLabel = QtGui.QLabel(self.bearingFrame)
        self.manualLonLabel.setGeometry(QtCore.QRect(190, 100, 71, 16))
        font = QtGui.QFont()
        font.setItalic(True)
        self.manualLonLabel.setFont(font)
        self.manualLonLabel.setObjectName("manualLonLabel")
        self.manualLat = QtGui.QLineEdit(self.bearingFrame)
        self.manualLat.setGeometry(QtCore.QRect(230, 60, 113, 20))
        self.manualLat.setInputMask("")
        self.manualLat.setText("")
        self.manualLat.setObjectName("manualLat")
        self.manualLatLabel = QtGui.QLabel(self.bearingFrame)
        self.manualLatLabel.setGeometry(QtCore.QRect(190, 40, 71, 16))
        font = QtGui.QFont()
        font.setItalic(True)
        self.manualLatLabel.setFont(font)
        self.manualLatLabel.setObjectName("manualLatLabel")
        self.manualSettingsEntryLabel = QtGui.QLabel(self.bearingFrame)
        self.manualSettingsEntryLabel.setGeometry(QtCore.QRect(190, 10, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.manualSettingsEntryLabel.setFont(font)
        self.manualSettingsEntryLabel.setObjectName("manualSettingsEntryLabel")
        self.autoFrame = QtGui.QFrame(self.Settings)
        self.autoFrame.setGeometry(QtCore.QRect(450, 30, 391, 261))
        self.autoFrame.setFrameShape(QtGui.QFrame.WinPanel)
        self.autoFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.autoFrame.setObjectName("autoFrame")
        self.gridLayoutWidget_2 = QtGui.QWidget(self.autoFrame)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 151, 211))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.autoGrid = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.autoGrid.setContentsMargins(0, 0, 0, 0)
        self.autoGrid.setObjectName("autoGrid")
        self.autoHybrid = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.autoHybrid.setEnabled(False)
        self.autoHybrid.setObjectName("autoHybrid")
        self.autoGrid.addWidget(self.autoHybrid, 5, 0, 1, 1)
        self.autoDisabled = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.autoDisabled.setObjectName("autoDisabled")
        self.autoGrid.addWidget(self.autoDisabled, 0, 0, 1, 1)
        self.autoRFD = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.autoRFD.setObjectName("autoRFD")
        self.autoGrid.addWidget(self.autoRFD, 4, 0, 1, 1)
        self.autoIridium = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.autoIridium.setChecked(True)
        self.autoIridium.setObjectName("autoIridium")
        self.autoGrid.addWidget(self.autoIridium, 2, 0, 1, 1)
        self.autoIridiumPredict = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.autoIridiumPredict.setObjectName("autoIridiumPredict")
        self.autoGrid.addWidget(self.autoIridiumPredict, 3, 0, 1, 1)
        self.autoSimulation = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.autoSimulation.setObjectName("autoSimulation")
        self.autoGrid.addWidget(self.autoSimulation, 1, 0, 1, 1)
        self.autotrackLabel = QtGui.QLabel(self.autoFrame)
        self.autotrackLabel.setGeometry(QtCore.QRect(10, 10, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.autotrackLabel.setFont(font)
        self.autotrackLabel.setObjectName("autotrackLabel")
        self.simulationFlightLabel = QtGui.QLabel(self.autoFrame)
        self.simulationFlightLabel.setGeometry(QtCore.QRect(190, 10, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.simulationFlightLabel.setFont(font)
        self.simulationFlightLabel.setObjectName("simulationFlightLabel")
        self.simDateLabel = QtGui.QLabel(self.autoFrame)
        self.simDateLabel.setGeometry(QtCore.QRect(190, 30, 111, 16))
        font = QtGui.QFont()
        font.setItalic(True)
        self.simDateLabel.setFont(font)
        self.simDateLabel.setObjectName("simDateLabel")
        self.simDate = QtGui.QLineEdit(self.autoFrame)
        self.simDate.setGeometry(QtCore.QRect(210, 50, 113, 20))
        self.simDate.setText("")
        self.simDate.setObjectName("simDate")
        self.simAltLabel = QtGui.QLabel(self.autoFrame)
        self.simAltLabel.setGeometry(QtCore.QRect(190, 70, 141, 16))
        font = QtGui.QFont()
        font.setItalic(True)
        self.simAltLabel.setFont(font)
        self.simAltLabel.setObjectName("simAltLabel")
        self.simAlt = QtGui.QLineEdit(self.autoFrame)
        self.simAlt.setGeometry(QtCore.QRect(210, 90, 113, 20))
        self.simAlt.setText("")
        self.simAlt.setObjectName("simAlt")
        self.pointLong = QtGui.QLineEdit(self.autoFrame)
        self.pointLong.setGeometry(QtCore.QRect(210, 230, 113, 20))
        self.pointLong.setText("")
        self.pointLong.setObjectName("pointLong")
        self.pointLat = QtGui.QLineEdit(self.autoFrame)
        self.pointLat.setGeometry(QtCore.QRect(210, 190, 113, 20))
        self.pointLat.setText("")
        self.pointLat.setObjectName("pointLat")
        self.pointtolatitudelabel = QtGui.QLabel(self.autoFrame)
        self.pointtolatitudelabel.setGeometry(QtCore.QRect(190, 170, 141, 16))
        font = QtGui.QFont()
        font.setItalic(True)
        self.pointtolatitudelabel.setFont(font)
        self.pointtolatitudelabel.setObjectName("pointtolatitudelabel")
        self.pointtolongitudelabel = QtGui.QLabel(self.autoFrame)
        self.pointtolongitudelabel.setGeometry(QtCore.QRect(190, 210, 141, 16))
        font = QtGui.QFont()
        font.setItalic(True)
        self.pointtolongitudelabel.setFont(font)
        self.pointtolongitudelabel.setObjectName("pointtolongitudelabel")
        self.pointAlt = QtGui.QLineEdit(self.autoFrame)
        self.pointAlt.setGeometry(QtCore.QRect(210, 150, 113, 20))
        self.pointAlt.setText("")
        self.pointAlt.setObjectName("pointAlt")
        self.pointtoaltitudelabel = QtGui.QLabel(self.autoFrame)
        self.pointtoaltitudelabel.setGeometry(QtCore.QRect(190, 130, 141, 16))
        font = QtGui.QFont()
        font.setItalic(True)
        self.pointtoaltitudelabel.setFont(font)
        self.pointtoaltitudelabel.setObjectName("pointtoaltitudelabel")
        self.simulationFlightLabel_2 = QtGui.QLabel(self.autoFrame)
        self.simulationFlightLabel_2.setGeometry(QtCore.QRect(180, 110, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.simulationFlightLabel_2.setFont(font)
        self.simulationFlightLabel_2.setObjectName("simulationFlightLabel_2")
        self.PointButton = QtGui.QPushButton(self.autoFrame)
        self.PointButton.setGeometry(QtCore.QRect(330, 210, 51, 41))
        self.PointButton.setObjectName("PointButton")
        self.launchFrame = QtGui.QFrame(self.Settings)
        self.launchFrame.setGeometry(QtCore.QRect(570, 300, 271, 221))
        self.launchFrame.setFrameShape(QtGui.QFrame.WinPanel)
        self.launchFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.launchFrame.setObjectName("launchFrame")
        self.updateSettings = QtGui.QCommandLinkButton(self.launchFrame)
        self.updateSettings.setGeometry(QtCore.QRect(30, 10, 221, 41))
        self.updateSettings.setObjectName("updateSettings")
        self.antennaCenter = QtGui.QCommandLinkButton(self.launchFrame)
        self.antennaCenter.setGeometry(QtCore.QRect(30, 60, 221, 41))
        self.antennaCenter.setObjectName("antennaCenter")
        self.trackerLaunch = QtGui.QCommandLinkButton(self.launchFrame)
        self.trackerLaunch.setGeometry(QtCore.QRect(30, 160, 211, 41))
        self.trackerLaunch.setObjectName("trackerLaunch")
        self.motionTest = QtGui.QCommandLinkButton(self.launchFrame)
        self.motionTest.setGeometry(QtCore.QRect(30, 110, 221, 41))
        self.motionTest.setObjectName("motionTest")
        self.connectionFrame = QtGui.QFrame(self.Settings)
        self.connectionFrame.setGeometry(QtCore.QRect(30, 300, 271, 221))
        self.connectionFrame.setFrameShape(QtGui.QFrame.WinPanel)
        self.connectionFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.connectionFrame.setObjectName("connectionFrame")
        self.label_12 = QtGui.QLabel(self.connectionFrame)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayoutWidget_6 = QtGui.QWidget(self.connectionFrame)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 40, 251, 121))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.connectionGrid = QtGui.QGridLayout(self.gridLayoutWidget_6)
        self.connectionGrid.setContentsMargins(0, 0, 0, 0)
        self.connectionGrid.setObjectName("connectionGrid")
        self.arduinoAttached = QtGui.QCheckBox(self.gridLayoutWidget_6)
        self.arduinoAttached.setChecked(True)
        self.arduinoAttached.setObjectName("arduinoAttached")
        self.connectionGrid.addWidget(self.arduinoAttached, 2, 0, 1, 1)
        self.servoAttached = QtGui.QCheckBox(self.gridLayoutWidget_6)
        self.servoAttached.setChecked(True)
        self.servoAttached.setObjectName("servoAttached")
        self.connectionGrid.addWidget(self.servoAttached, 0, 0, 1, 1)
        self.servoCOM = QtGui.QLineEdit(self.gridLayoutWidget_6)
        self.servoCOM.setObjectName("servoCOM")
        self.connectionGrid.addWidget(self.servoCOM, 0, 1, 1, 1)
        self.rfdAttached = QtGui.QCheckBox(self.gridLayoutWidget_6)
        self.rfdAttached.setObjectName("rfdAttached")
        self.connectionGrid.addWidget(self.rfdAttached, 1, 0, 1, 1)
        self.arduinoCOM = QtGui.QLineEdit(self.gridLayoutWidget_6)
        self.arduinoCOM.setText("")
        self.arduinoCOM.setObjectName("arduinoCOM")
        self.connectionGrid.addWidget(self.arduinoCOM, 2, 1, 1, 1)
        self.rfdCOM = QtGui.QLineEdit(self.gridLayoutWidget_6)
        self.rfdCOM.setObjectName("rfdCOM")
        self.connectionGrid.addWidget(self.rfdCOM, 1, 1, 1, 1)
        self.calibrationGoalVal = QtGui.QLineEdit(self.gridLayoutWidget_6)
        self.calibrationGoalVal.setText("")
        self.calibrationGoalVal.setObjectName("calibrationGoalVal")
        self.connectionGrid.addWidget(self.calibrationGoalVal, 3, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget_6)
        self.label_2.setObjectName("label_2")
        self.connectionGrid.addWidget(self.label_2, 3, 0, 1, 1)
        self.simDateLabel_3 = QtGui.QLabel(self.connectionFrame)
        self.simDateLabel_3.setGeometry(QtCore.QRect(150, 20, 51, 16))
        font = QtGui.QFont()
        font.setItalic(True)
        self.simDateLabel_3.setFont(font)
        self.simDateLabel_3.setObjectName("simDateLabel_3")
        self.connectionFrame_2 = QtGui.QFrame(self.Settings)
        self.connectionFrame_2.setGeometry(QtCore.QRect(300, 300, 271, 221))
        self.connectionFrame_2.setFrameShape(QtGui.QFrame.WinPanel)
        self.connectionFrame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.connectionFrame_2.setObjectName("connectionFrame_2")
        self.label_13 = QtGui.QLabel(self.connectionFrame_2)
        self.label_13.setGeometry(QtCore.QRect(10, 10, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayoutWidget_7 = QtGui.QWidget(self.connectionFrame_2)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(10, 40, 251, 161))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.connectionGrid_2 = QtGui.QGridLayout(self.gridLayoutWidget_7)
        self.connectionGrid_2.setContentsMargins(0, 0, 0, 0)
        self.connectionGrid_2.setObjectName("connectionGrid_2")
        self.graphReal = QtGui.QRadioButton(self.gridLayoutWidget_7)
        self.graphReal.setChecked(True)
        self.graphReal.setObjectName("graphReal")
        self.connectionGrid_2.addWidget(self.graphReal, 0, 0, 1, 1)
        self.graphSQL = QtGui.QRadioButton(self.gridLayoutWidget_7)
        self.graphSQL.setObjectName("graphSQL")
        self.connectionGrid_2.addWidget(self.graphSQL, 1, 0, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.gridLayoutWidget_7)
        self.checkBox.setEnabled(False)
        self.checkBox.setObjectName("checkBox")
        self.connectionGrid_2.addWidget(self.checkBox, 2, 0, 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(self.gridLayoutWidget_7)
        self.checkBox_2.setEnabled(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.connectionGrid_2.addWidget(self.checkBox_2, 3, 0, 1, 1)
        self.tabs.addTab(self.Settings, "")
        self.Tracker = QtGui.QWidget()
        self.Tracker.setObjectName("Tracker")
        self.frame = QtGui.QFrame(self.Tracker)
        self.frame.setGeometry(QtCore.QRect(0, -3, 911, 601))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 150, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 150, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 150, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 150, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame.setPalette(palette)
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.trackerAni = QtGui.QGraphicsView(self.frame)
        self.trackerAni.setEnabled(False)
        self.trackerAni.setGeometry(QtCore.QRect(139, 27, 511, 491))
        self.trackerAni.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.trackerAni.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.trackerAni.setAlignment(QtCore.Qt.AlignCenter)
        self.trackerAni.setObjectName("trackerAni")
        self.widget = QtGui.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(10, 10, 831, 531))
        self.widget.setObjectName("widget")
        self.hSlider = QtGui.QSlider(self.frame)
        self.hSlider.setGeometry(QtCore.QRect(19, 560, 821, 22))
        self.hSlider.setMinimum(-180)
        self.hSlider.setMaximum(180)
        self.hSlider.setOrientation(QtCore.Qt.Horizontal)
        self.hSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.hSlider.setObjectName("hSlider")
        self.vSlider = QtGui.QSlider(self.frame)
        self.vSlider.setGeometry(QtCore.QRect(860, 19, 22, 521))
        self.vSlider.setMinimum(-180)
        self.vSlider.setMaximum(180)
        self.vSlider.setOrientation(QtCore.Qt.Vertical)
        self.vSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.vSlider.setObjectName("vSlider")
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(850, 550, 47, 16))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(850, 560, 47, 16))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.tabs.addTab(self.Tracker, "")
        self.Webview = QtGui.QWidget()
        self.Webview.setObjectName("Webview")
        self.webView = QtWebKit.QWebView(self.Webview)
        self.webView.setGeometry(QtCore.QRect(0, 0, 901, 581))
        self.webView.setUrl(QtCore.QUrl("http://153.90.202.22/"))
        self.webView.setZoomFactor(0.800000011921)
        self.webView.setRenderHints(QtGui.QPainter.HighQualityAntialiasing|QtGui.QPainter.SmoothPixmapTransform|QtGui.QPainter.TextAntialiasing)
        self.webView.setObjectName("webView")
        self.tabs.addTab(self.Webview, "")
        self.IridiumCommands = QtGui.QWidget()
        self.IridiumCommands.setEnabled(False)
        self.IridiumCommands.setObjectName("IridiumCommands")
        self.countdown = QtGui.QLCDNumber(self.IridiumCommands)
        self.countdown.setGeometry(QtCore.QRect(280, 240, 211, 61))
        self.countdown.setObjectName("countdown")
        self.countdownLabel = QtGui.QLabel(self.IridiumCommands)
        self.countdownLabel.setGeometry(QtCore.QRect(70, 260, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.countdownLabel.setFont(font)
        self.countdownLabel.setObjectName("countdownLabel")
        self.frame_2 = QtGui.QFrame(self.IridiumCommands)
        self.frame_2.setGeometry(QtCore.QRect(110, 30, 651, 91))
        self.frame_2.setFrameShape(QtGui.QFrame.WinPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.openValveCmd = QtGui.QPushButton(self.frame_2)
        self.openValveCmd.setGeometry(QtCore.QRect(10, 10, 151, 71))
        self.openValveCmd.setObjectName("openValveCmd")
        self.posiedonCmd = QtGui.QPushButton(self.frame_2)
        self.posiedonCmd.setGeometry(QtCore.QRect(330, 10, 151, 71))
        self.posiedonCmd.setObjectName("posiedonCmd")
        self.closeValveCmd = QtGui.QPushButton(self.frame_2)
        self.closeValveCmd.setGeometry(QtCore.QRect(170, 10, 151, 71))
        self.closeValveCmd.setObjectName("closeValveCmd")
        self.cutdownCmd = QtGui.QPushButton(self.frame_2)
        self.cutdownCmd.setGeometry(QtCore.QRect(490, 10, 151, 71))
        self.cutdownCmd.setObjectName("cutdownCmd")
        self.sendingLabel = QtGui.QLabel(self.IridiumCommands)
        self.sendingLabel.setGeometry(QtCore.QRect(70, 390, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.sendingLabel.setFont(font)
        self.sendingLabel.setObjectName("sendingLabel")
        self.sendCmd = QtGui.QLabel(self.IridiumCommands)
        self.sendCmd.setGeometry(QtCore.QRect(280, 370, 421, 91))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.sendCmd.setFont(font)
        self.sendCmd.setObjectName("sendCmd")
        self.abortCmd = QtGui.QPushButton(self.IridiumCommands)
        self.abortCmd.setGeometry(QtCore.QRect(590, 240, 161, 61))
        self.abortCmd.setObjectName("abortCmd")
        self.tabs.addTab(self.IridiumCommands, "")
        self.statusLabel = QtGui.QLabel(self.centralwidget)
        self.statusLabel.setGeometry(QtCore.QRect(510, 610, 191, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.statusLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(24)
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.statusLabel.setFont(font)
        self.statusLabel.setObjectName("statusLabel")
        self.status = QtGui.QLabel(self.centralwidget)
        self.status.setGeometry(QtCore.QRect(830, 610, 191, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(243, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.status.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(24)
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.status.setFont(font)
        self.status.setObjectName("status")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1300, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.incomingData, self.groundData)
        MainWindow.setTabOrder(self.groundData, self.tabs)
        MainWindow.setTabOrder(self.tabs, self.webView)
        MainWindow.setTabOrder(self.webView, self.getLocal)
        MainWindow.setTabOrder(self.getLocal, self.bearingNorth)
        MainWindow.setTabOrder(self.bearingNorth, self.bearingEast)
        MainWindow.setTabOrder(self.bearingEast, self.bearingSouth)
        MainWindow.setTabOrder(self.bearingSouth, self.bearingWest)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.incomingLabel.setText(QtGui.QApplication.translate("MainWindow", "Incoming GPS Data:", None, QtGui.QApplication.UnicodeUTF8))
        self.incomingData.verticalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Last Received Time", None, QtGui.QApplication.UnicodeUTF8))
        self.incomingData.verticalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Latitude", None, QtGui.QApplication.UnicodeUTF8))
        self.incomingData.verticalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Longitude", None, QtGui.QApplication.UnicodeUTF8))
        self.incomingData.verticalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Altitude", None, QtGui.QApplication.UnicodeUTF8))
        self.incomingData.verticalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Elevation Angle", None, QtGui.QApplication.UnicodeUTF8))
        self.incomingData.verticalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Bearing (From North)", None, QtGui.QApplication.UnicodeUTF8))
        self.incomingData.verticalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "Line-of-Sight (km)", None, QtGui.QApplication.UnicodeUTF8))
        self.incomingData.verticalHeaderItem(7).setText(QtGui.QApplication.translate("MainWindow", "Mag Declination", None, QtGui.QApplication.UnicodeUTF8))
        self.incomingData.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.groundData.verticalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Latitude", None, QtGui.QApplication.UnicodeUTF8))
        self.groundData.verticalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Longitude", None, QtGui.QApplication.UnicodeUTF8))
        self.groundData.verticalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Altitude", None, QtGui.QApplication.UnicodeUTF8))
        self.groundData.verticalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Center Bearing (N)", None, QtGui.QApplication.UnicodeUTF8))
        self.groundData.verticalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Applied Bearing Offset", None, QtGui.QApplication.UnicodeUTF8))
        self.groundData.verticalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Applied Tilt Offset", None, QtGui.QApplication.UnicodeUTF8))
        self.groundData.verticalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "Bearing Position", None, QtGui.QApplication.UnicodeUTF8))
        self.groundData.verticalHeaderItem(7).setText(QtGui.QApplication.translate("MainWindow", "Elevation Position", None, QtGui.QApplication.UnicodeUTF8))
        self.groundData.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.groundLabel.setText(QtGui.QApplication.translate("MainWindow", "Ground Station Data:", None, QtGui.QApplication.UnicodeUTF8))
        self.getLocal.setText(QtGui.QApplication.translate("MainWindow", "Get Local (Arduino)", None, QtGui.QApplication.UnicodeUTF8))
        self.bearingSouth.setText(QtGui.QApplication.translate("MainWindow", "South Facing", None, QtGui.QApplication.UnicodeUTF8))
        self.bearingEast.setText(QtGui.QApplication.translate("MainWindow", "East Facing", None, QtGui.QApplication.UnicodeUTF8))
        self.bearingWest.setText(QtGui.QApplication.translate("MainWindow", "West Facing", None, QtGui.QApplication.UnicodeUTF8))
        self.bearingNorth.setText(QtGui.QApplication.translate("MainWindow", "North Facing", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Center Bearing (True):", None, QtGui.QApplication.UnicodeUTF8))
        self.manualAlt.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "4934", None, QtGui.QApplication.UnicodeUTF8))
        self.manualAltLabel.setText(QtGui.QApplication.translate("MainWindow", "Altitude (ft):", None, QtGui.QApplication.UnicodeUTF8))
        self.manualLon.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "-111.0445833", None, QtGui.QApplication.UnicodeUTF8))
        self.manualLonLabel.setText(QtGui.QApplication.translate("MainWindow", "Longitude (°):", None, QtGui.QApplication.UnicodeUTF8))
        self.manualLat.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "45.6629505", None, QtGui.QApplication.UnicodeUTF8))
        self.manualLatLabel.setText(QtGui.QApplication.translate("MainWindow", "Latitude (°):", None, QtGui.QApplication.UnicodeUTF8))
        self.manualSettingsEntryLabel.setText(QtGui.QApplication.translate("MainWindow", "Manual Settings Entry:", None, QtGui.QApplication.UnicodeUTF8))
        self.autoHybrid.setText(QtGui.QApplication.translate("MainWindow", "Hybrid (RFD900 + Iridium)", None, QtGui.QApplication.UnicodeUTF8))
        self.autoDisabled.setText(QtGui.QApplication.translate("MainWindow", "Disabled", None, QtGui.QApplication.UnicodeUTF8))
        self.autoRFD.setText(QtGui.QApplication.translate("MainWindow", "RFD900", None, QtGui.QApplication.UnicodeUTF8))
        self.autoIridium.setText(QtGui.QApplication.translate("MainWindow", "Iridium", None, QtGui.QApplication.UnicodeUTF8))
        self.autoIridiumPredict.setText(QtGui.QApplication.translate("MainWindow", "Iridium + Prediction", None, QtGui.QApplication.UnicodeUTF8))
        self.autoSimulation.setText(QtGui.QApplication.translate("MainWindow", "Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.autotrackLabel.setText(QtGui.QApplication.translate("MainWindow", "AutoTrack:", None, QtGui.QApplication.UnicodeUTF8))
        self.simulationFlightLabel.setText(QtGui.QApplication.translate("MainWindow", "Simulation Flight:", None, QtGui.QApplication.UnicodeUTF8))
        self.simDateLabel.setText(QtGui.QApplication.translate("MainWindow", "Date (yyyy-mm-dd):", None, QtGui.QApplication.UnicodeUTF8))
        self.simDate.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "2015-04-10", None, QtGui.QApplication.UnicodeUTF8))
        self.simAltLabel.setText(QtGui.QApplication.translate("MainWindow", "Simulation Start Alt (meters):", None, QtGui.QApplication.UnicodeUTF8))
        self.simAlt.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "1000", None, QtGui.QApplication.UnicodeUTF8))
        self.pointLong.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "-111.0445833", None, QtGui.QApplication.UnicodeUTF8))
        self.pointLat.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "45.6629505", None, QtGui.QApplication.UnicodeUTF8))
        self.pointtolatitudelabel.setText(QtGui.QApplication.translate("MainWindow", "Point-To Latitude (°):", None, QtGui.QApplication.UnicodeUTF8))
        self.pointtolongitudelabel.setText(QtGui.QApplication.translate("MainWindow", "Point-To Longitude (°):", None, QtGui.QApplication.UnicodeUTF8))
        self.pointAlt.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "5000", None, QtGui.QApplication.UnicodeUTF8))
        self.pointtoaltitudelabel.setText(QtGui.QApplication.translate("MainWindow", "Point-To Altitude(ft):", None, QtGui.QApplication.UnicodeUTF8))
        self.simulationFlightLabel_2.setText(QtGui.QApplication.translate("MainWindow", "Point-To Coordinates:", None, QtGui.QApplication.UnicodeUTF8))
        self.PointButton.setText(QtGui.QApplication.translate("MainWindow", "Point-To", None, QtGui.QApplication.UnicodeUTF8))
        self.updateSettings.setText(QtGui.QApplication.translate("MainWindow", "Update Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.antennaCenter.setText(QtGui.QApplication.translate("MainWindow", "Move Antennas to Center", None, QtGui.QApplication.UnicodeUTF8))
        self.trackerLaunch.setText(QtGui.QApplication.translate("MainWindow", "Launch Antenna Tracker", None, QtGui.QApplication.UnicodeUTF8))
        self.motionTest.setText(QtGui.QApplication.translate("MainWindow", "Range of Motion Test ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Connections:", None, QtGui.QApplication.UnicodeUTF8))
        self.arduinoAttached.setText(QtGui.QApplication.translate("MainWindow", "Arduino Connected", None, QtGui.QApplication.UnicodeUTF8))
        self.servoAttached.setText(QtGui.QApplication.translate("MainWindow", "Servos Connected", None, QtGui.QApplication.UnicodeUTF8))
        self.servoCOM.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "COM8", None, QtGui.QApplication.UnicodeUTF8))
        self.rfdAttached.setText(QtGui.QApplication.translate("MainWindow", "RFD Connected", None, QtGui.QApplication.UnicodeUTF8))
        self.arduinoCOM.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "COM7", None, QtGui.QApplication.UnicodeUTF8))
        self.rfdCOM.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "COM24", None, QtGui.QApplication.UnicodeUTF8))
        self.calibrationGoalVal.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "      Calibration Goal", None, QtGui.QApplication.UnicodeUTF8))
        self.simDateLabel_3.setText(QtGui.QApplication.translate("MainWindow", "COM Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Graphing and Logging:", None, QtGui.QApplication.UnicodeUTF8))
        self.graphReal.setText(QtGui.QApplication.translate("MainWindow", "Graph Runtime", None, QtGui.QApplication.UnicodeUTF8))
        self.graphSQL.setText(QtGui.QApplication.translate("MainWindow", "Graph SQL Data", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("MainWindow", "Save CSV of Flight Data", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("MainWindow", "Save CSV of Prediction Data", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.Settings), QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Antenna", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Adjust", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.Tracker), QtGui.QApplication.translate("MainWindow", "Tracker", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.Webview), QtGui.QApplication.translate("MainWindow", "Webview", None, QtGui.QApplication.UnicodeUTF8))
        self.countdownLabel.setText(QtGui.QApplication.translate("MainWindow", "Count Down:", None, QtGui.QApplication.UnicodeUTF8))
        self.openValveCmd.setText(QtGui.QApplication.translate("MainWindow", "Open Valve", None, QtGui.QApplication.UnicodeUTF8))
        self.posiedonCmd.setText(QtGui.QApplication.translate("MainWindow", "Posiedon", None, QtGui.QApplication.UnicodeUTF8))
        self.closeValveCmd.setText(QtGui.QApplication.translate("MainWindow", "Close Valve", None, QtGui.QApplication.UnicodeUTF8))
        self.cutdownCmd.setText(QtGui.QApplication.translate("MainWindow", "Cutdown", None, QtGui.QApplication.UnicodeUTF8))
        self.sendingLabel.setText(QtGui.QApplication.translate("MainWindow", "Sending...", None, QtGui.QApplication.UnicodeUTF8))
        self.sendCmd.setText(QtGui.QApplication.translate("MainWindow", "____________________", None, QtGui.QApplication.UnicodeUTF8))
        self.abortCmd.setText(QtGui.QApplication.translate("MainWindow", "Abort", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.IridiumCommands), QtGui.QApplication.translate("MainWindow", "Iridium Commands", None, QtGui.QApplication.UnicodeUTF8))
        self.statusLabel.setText(QtGui.QApplication.translate("MainWindow", "Autotrack: ", None, QtGui.QApplication.UnicodeUTF8))
        self.status.setText(QtGui.QApplication.translate("MainWindow", "Offline", None, QtGui.QApplication.UnicodeUTF8))

from PySide import QtWebKit
