# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trackermain.ui',
# licensing of 'trackermain.ui' applies.
#
# Created: Tue Jun  4 14:34:42 2019
#      by: pyside2-uic  running on PySide2 5.12.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 690)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.incomingLabel = QtWidgets.QLabel(self.centralwidget)
        self.incomingLabel.setGeometry(QtCore.QRect(10, 20, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.incomingLabel.setFont(font)
        self.incomingLabel.setObjectName("incomingLabel")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(260, 10, 21, 631))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.incomingData = QtWidgets.QTableWidget(self.centralwidget)
        self.incomingData.setGeometry(QtCore.QRect(20, 40, 221, 271))
        self.incomingData.setAutoScroll(False)
        self.incomingData.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.incomingData.setTabKeyNavigation(False)
        self.incomingData.setObjectName("incomingData")
        self.incomingData.setColumnCount(1)
        self.incomingData.setRowCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.incomingData.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.incomingData.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.incomingData.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.incomingData.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.incomingData.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.incomingData.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.incomingData.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.incomingData.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.incomingData.setHorizontalHeaderItem(0, item)
        self.groundData = QtWidgets.QTableWidget(self.centralwidget)
        self.groundData.setGeometry(QtCore.QRect(10, 360, 251, 271))
        self.groundData.setAutoScroll(False)
        self.groundData.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.groundData.setTabKeyNavigation(False)
        self.groundData.setObjectName("groundData")
        self.groundData.setColumnCount(1)
        self.groundData.setRowCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.groundData.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.groundData.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.groundData.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.groundData.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.groundData.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.groundData.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.groundData.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.groundData.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.groundData.setHorizontalHeaderItem(0, item)
        self.groundLabel = QtWidgets.QLabel(self.centralwidget)
        self.groundLabel.setGeometry(QtCore.QRect(20, 340, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.groundLabel.setFont(font)
        self.groundLabel.setObjectName("groundLabel")
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setEnabled(True)
        self.tabs.setGeometry(QtCore.QRect(280, 0, 931, 601))
        self.tabs.setAutoFillBackground(True)
        self.tabs.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabs.setObjectName("tabs")
        self.Settings = QtWidgets.QWidget()
        self.Settings.setObjectName("Settings")
        self.bearingFrame = QtWidgets.QFrame(self.Settings)
        self.bearingFrame.setGeometry(QtCore.QRect(30, 30, 391, 261))
        self.bearingFrame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.bearingFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bearingFrame.setObjectName("bearingFrame")
        self.gridLayoutWidget = QtWidgets.QWidget(self.bearingFrame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 30, 131, 211))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.bearingGrid = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.bearingGrid.setContentsMargins(0, 0, 0, 0)
        self.bearingGrid.setObjectName("bearingGrid")
        self.getLocal = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.getLocal.setChecked(True)
        self.getLocal.setObjectName("getLocal")
        self.bearingGrid.addWidget(self.getLocal, 0, 0, 1, 1)
        self.bearingSouth = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.bearingSouth.setObjectName("bearingSouth")
        self.bearingGrid.addWidget(self.bearingSouth, 3, 0, 1, 1)
        self.bearingEast = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.bearingEast.setObjectName("bearingEast")
        self.bearingGrid.addWidget(self.bearingEast, 2, 0, 1, 1)
        self.bearingWest = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.bearingWest.setObjectName("bearingWest")
        self.bearingGrid.addWidget(self.bearingWest, 4, 0, 1, 1)
        self.bearingNorth = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.bearingNorth.setObjectName("bearingNorth")
        self.bearingGrid.addWidget(self.bearingNorth, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.bearingFrame)
        self.label.setGeometry(QtCore.QRect(10, 10, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.manualAlt = QtWidgets.QLineEdit(self.bearingFrame)
        self.manualAlt.setGeometry(QtCore.QRect(230, 180, 113, 20))
        self.manualAlt.setText("")
        self.manualAlt.setObjectName("manualAlt")
        self.manualAltLabel = QtWidgets.QLabel(self.bearingFrame)
        self.manualAltLabel.setGeometry(QtCore.QRect(190, 160, 61, 16))
        font = QtGui.QFont()
        font.setItalic(True)
        self.manualAltLabel.setFont(font)
        self.manualAltLabel.setObjectName("manualAltLabel")
        self.manualLon = QtWidgets.QLineEdit(self.bearingFrame)
        self.manualLon.setGeometry(QtCore.QRect(230, 120, 113, 20))
        self.manualLon.setText("")
        self.manualLon.setObjectName("manualLon")
        self.manualLonLabel = QtWidgets.QLabel(self.bearingFrame)
        self.manualLonLabel.setGeometry(QtCore.QRect(190, 100, 71, 16))
        font = QtGui.QFont()
        font.setItalic(True)
        self.manualLonLabel.setFont(font)
        self.manualLonLabel.setObjectName("manualLonLabel")
        self.manualLat = QtWidgets.QLineEdit(self.bearingFrame)
        self.manualLat.setGeometry(QtCore.QRect(230, 60, 113, 20))
        self.manualLat.setInputMask("")
        self.manualLat.setText("")
        self.manualLat.setObjectName("manualLat")
        self.manualLatLabel = QtWidgets.QLabel(self.bearingFrame)
        self.manualLatLabel.setGeometry(QtCore.QRect(190, 40, 71, 16))
        font = QtGui.QFont()
        font.setItalic(True)
        self.manualLatLabel.setFont(font)
        self.manualLatLabel.setObjectName("manualLatLabel")
        self.manualSettingsEntryLabel = QtWidgets.QLabel(self.bearingFrame)
        self.manualSettingsEntryLabel.setGeometry(QtCore.QRect(190, 10, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.manualSettingsEntryLabel.setFont(font)
        self.manualSettingsEntryLabel.setObjectName("manualSettingsEntryLabel")
        self.autoFrame = QtWidgets.QFrame(self.Settings)
        self.autoFrame.setGeometry(QtCore.QRect(450, 30, 391, 261))
        self.autoFrame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.autoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.autoFrame.setObjectName("autoFrame")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.autoFrame)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 151, 211))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.autoGrid = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.autoGrid.setContentsMargins(0, 0, 0, 0)
        self.autoGrid.setObjectName("autoGrid")
        self.autoHybrid = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.autoHybrid.setEnabled(False)
        self.autoHybrid.setObjectName("autoHybrid")
        self.autoGrid.addWidget(self.autoHybrid, 5, 0, 1, 1)
        self.autoDisabled = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.autoDisabled.setObjectName("autoDisabled")
        self.autoGrid.addWidget(self.autoDisabled, 0, 0, 1, 1)
        self.autoRFD = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.autoRFD.setObjectName("autoRFD")
        self.autoGrid.addWidget(self.autoRFD, 4, 0, 1, 1)
        self.autoIridium = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.autoIridium.setChecked(True)
        self.autoIridium.setObjectName("autoIridium")
        self.autoGrid.addWidget(self.autoIridium, 2, 0, 1, 1)
        self.autoIridiumPredict = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.autoIridiumPredict.setObjectName("autoIridiumPredict")
        self.autoGrid.addWidget(self.autoIridiumPredict, 3, 0, 1, 1)
        self.autoSimulation = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.autoSimulation.setObjectName("autoSimulation")
        self.autoGrid.addWidget(self.autoSimulation, 1, 0, 1, 1)
        self.autotrackLabel = QtWidgets.QLabel(self.autoFrame)
        self.autotrackLabel.setGeometry(QtCore.QRect(10, 10, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.autotrackLabel.setFont(font)
        self.autotrackLabel.setObjectName("autotrackLabel")
        self.simulationFlightLabel = QtWidgets.QLabel(self.autoFrame)
        self.simulationFlightLabel.setGeometry(QtCore.QRect(190, 10, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.simulationFlightLabel.setFont(font)
        self.simulationFlightLabel.setObjectName("simulationFlightLabel")
        self.simDateLabel = QtWidgets.QLabel(self.autoFrame)
        self.simDateLabel.setGeometry(QtCore.QRect(190, 30, 111, 16))
        font = QtGui.QFont()
        font.setItalic(True)
        self.simDateLabel.setFont(font)
        self.simDateLabel.setObjectName("simDateLabel")
        self.simDate = QtWidgets.QLineEdit(self.autoFrame)
        self.simDate.setGeometry(QtCore.QRect(210, 50, 113, 20))
        self.simDate.setText("")
        self.simDate.setObjectName("simDate")
        self.simAltLabel = QtWidgets.QLabel(self.autoFrame)
        self.simAltLabel.setGeometry(QtCore.QRect(190, 70, 141, 16))
        font = QtGui.QFont()
        font.setItalic(True)
        self.simAltLabel.setFont(font)
        self.simAltLabel.setObjectName("simAltLabel")
        self.simAlt = QtWidgets.QLineEdit(self.autoFrame)
        self.simAlt.setGeometry(QtCore.QRect(210, 90, 113, 20))
        self.simAlt.setText("")
        self.simAlt.setObjectName("simAlt")
        self.pointLong = QtWidgets.QLineEdit(self.autoFrame)
        self.pointLong.setGeometry(QtCore.QRect(210, 230, 113, 20))
        self.pointLong.setText("")
        self.pointLong.setObjectName("pointLong")
        self.pointLat = QtWidgets.QLineEdit(self.autoFrame)
        self.pointLat.setGeometry(QtCore.QRect(210, 190, 113, 20))
        self.pointLat.setText("")
        self.pointLat.setObjectName("pointLat")
        self.pointtolatitudelabel = QtWidgets.QLabel(self.autoFrame)
        self.pointtolatitudelabel.setGeometry(QtCore.QRect(190, 170, 141, 16))
        font = QtGui.QFont()
        font.setItalic(True)
        self.pointtolatitudelabel.setFont(font)
        self.pointtolatitudelabel.setObjectName("pointtolatitudelabel")
        self.pointtolongitudelabel = QtWidgets.QLabel(self.autoFrame)
        self.pointtolongitudelabel.setGeometry(QtCore.QRect(190, 210, 141, 16))
        font = QtGui.QFont()
        font.setItalic(True)
        self.pointtolongitudelabel.setFont(font)
        self.pointtolongitudelabel.setObjectName("pointtolongitudelabel")
        self.pointAlt = QtWidgets.QLineEdit(self.autoFrame)
        self.pointAlt.setGeometry(QtCore.QRect(210, 150, 113, 20))
        self.pointAlt.setText("")
        self.pointAlt.setObjectName("pointAlt")
        self.pointtoaltitudelabel = QtWidgets.QLabel(self.autoFrame)
        self.pointtoaltitudelabel.setGeometry(QtCore.QRect(190, 130, 141, 16))
        font = QtGui.QFont()
        font.setItalic(True)
        self.pointtoaltitudelabel.setFont(font)
        self.pointtoaltitudelabel.setObjectName("pointtoaltitudelabel")
        self.simulationFlightLabel_2 = QtWidgets.QLabel(self.autoFrame)
        self.simulationFlightLabel_2.setGeometry(QtCore.QRect(180, 110, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.simulationFlightLabel_2.setFont(font)
        self.simulationFlightLabel_2.setObjectName("simulationFlightLabel_2")
        self.PointButton = QtWidgets.QPushButton(self.autoFrame)
        self.PointButton.setGeometry(QtCore.QRect(330, 210, 51, 41))
        self.PointButton.setObjectName("PointButton")
        self.launchFrame = QtWidgets.QFrame(self.Settings)
        self.launchFrame.setGeometry(QtCore.QRect(570, 300, 271, 221))
        self.launchFrame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.launchFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.launchFrame.setObjectName("launchFrame")
        self.updateSettings = QtWidgets.QCommandLinkButton(self.launchFrame)
        self.updateSettings.setGeometry(QtCore.QRect(10, 10, 221, 41))
        self.updateSettings.setObjectName("updateSettings")
        self.antennaCenter = QtWidgets.QCommandLinkButton(self.launchFrame)
        self.antennaCenter.setGeometry(QtCore.QRect(10, 90, 221, 41))
        self.antennaCenter.setObjectName("antennaCenter")
        self.trackerLaunch = QtWidgets.QCommandLinkButton(self.launchFrame)
        self.trackerLaunch.setGeometry(QtCore.QRect(10, 180, 211, 41))
        self.trackerLaunch.setObjectName("trackerLaunch")
        self.pointAtBalloon = QtWidgets.QCommandLinkButton(self.launchFrame)
        self.pointAtBalloon.setGeometry(QtCore.QRect(50, 130, 221, 41))
        self.pointAtBalloon.setObjectName("pointAtBalloon")
        self.recalibrateCenterBearing = QtWidgets.QCommandLinkButton(self.launchFrame)
        self.recalibrateCenterBearing.setGeometry(QtCore.QRect(60, 50, 172, 41))
        self.recalibrateCenterBearing.setObjectName("recalibrateCenterBearing")
        self.connectionFrame = QtWidgets.QFrame(self.Settings)
        self.connectionFrame.setGeometry(QtCore.QRect(30, 300, 531, 221))
        self.connectionFrame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.connectionFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.connectionFrame.setObjectName("connectionFrame")
        self.label_12 = QtWidgets.QLabel(self.connectionFrame)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.connectionFrame)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 40, 251, 121))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.connectionGrid = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.connectionGrid.setContentsMargins(0, 0, 0, 0)
        self.connectionGrid.setObjectName("connectionGrid")
        self.arduinoAttached = QtWidgets.QCheckBox(self.gridLayoutWidget_6)
        self.arduinoAttached.setChecked(True)
        self.arduinoAttached.setObjectName("arduinoAttached")
        self.connectionGrid.addWidget(self.arduinoAttached, 2, 0, 1, 1)
        self.servoAttached = QtWidgets.QCheckBox(self.gridLayoutWidget_6)
        self.servoAttached.setChecked(True)
        self.servoAttached.setObjectName("servoAttached")
        self.connectionGrid.addWidget(self.servoAttached, 0, 0, 1, 1)
        self.servoCOM = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.servoCOM.setObjectName("servoCOM")
        self.connectionGrid.addWidget(self.servoCOM, 0, 1, 1, 1)
        self.rfdAttached = QtWidgets.QCheckBox(self.gridLayoutWidget_6)
        self.rfdAttached.setObjectName("rfdAttached")
        self.connectionGrid.addWidget(self.rfdAttached, 1, 0, 1, 1)
        self.arduinoCOM = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.arduinoCOM.setText("")
        self.arduinoCOM.setObjectName("arduinoCOM")
        self.connectionGrid.addWidget(self.arduinoCOM, 2, 1, 1, 1)
        self.rfdCOM = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.rfdCOM.setObjectName("rfdCOM")
        self.connectionGrid.addWidget(self.rfdCOM, 1, 1, 1, 1)
        self.calibrationGoalVal = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.calibrationGoalVal.setText("")
        self.calibrationGoalVal.setObjectName("calibrationGoalVal")
        self.connectionGrid.addWidget(self.calibrationGoalVal, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_2.setObjectName("label_2")
        self.connectionGrid.addWidget(self.label_2, 3, 0, 1, 1)
        self.simDateLabel_3 = QtWidgets.QLabel(self.connectionFrame)
        self.simDateLabel_3.setGeometry(QtCore.QRect(150, 20, 51, 16))
        font = QtGui.QFont()
        font.setItalic(True)
        self.simDateLabel_3.setFont(font)
        self.simDateLabel_3.setObjectName("simDateLabel_3")
        self.checkComPorts = QtWidgets.QPushButton(self.connectionFrame)
        self.checkComPorts.setGeometry(QtCore.QRect(280, 40, 211, 121))
        self.checkComPorts.setObjectName("checkComPorts")
        self.tabs.addTab(self.Settings, "")
        self.Tracker = QtWidgets.QWidget()
        self.Tracker.setObjectName("Tracker")
        self.frame = QtWidgets.QFrame(self.Tracker)
        self.frame.setGeometry(QtCore.QRect(0, -3, 911, 601))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 150, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 217, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 150, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 150, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(150, 150, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame.setPalette(palette)
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.trackerAni = QtWidgets.QGraphicsView(self.frame)
        self.trackerAni.setEnabled(False)
        self.trackerAni.setGeometry(QtCore.QRect(139, 27, 511, 491))
        self.trackerAni.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.trackerAni.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.trackerAni.setAlignment(QtCore.Qt.AlignCenter)
        self.trackerAni.setObjectName("trackerAni")
        self.hSlider = QtWidgets.QSlider(self.frame)
        self.hSlider.setGeometry(QtCore.QRect(19, 560, 821, 22))
        self.hSlider.setMinimum(-180)
        self.hSlider.setMaximum(180)
        self.hSlider.setOrientation(QtCore.Qt.Horizontal)
        self.hSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.hSlider.setObjectName("hSlider")
        self.vSlider = QtWidgets.QSlider(self.frame)
        self.vSlider.setGeometry(QtCore.QRect(860, 19, 22, 521))
        self.vSlider.setMinimum(-180)
        self.vSlider.setMaximum(180)
        self.vSlider.setOrientation(QtCore.Qt.Vertical)
        self.vSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.vSlider.setObjectName("vSlider")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(850, 550, 47, 16))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(850, 560, 47, 16))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.tabs.addTab(self.Tracker, "")
        self.Commands = QtWidgets.QWidget()
        self.Commands.setEnabled(False)
        self.Commands.setObjectName("Commands")
        self.cutdownButton = QtWidgets.QPushButton(self.Commands)
        self.cutdownButton.setGeometry(QtCore.QRect(80, 40, 261, 201))
        self.cutdownButton.setObjectName("cutdownButton")
        self.idleButton = QtWidgets.QPushButton(self.Commands)
        self.idleButton.setGeometry(QtCore.QRect(90, 250, 261, 201))
        self.idleButton.setObjectName("idleButton")
        self.tabs.addTab(self.Commands, "")
        self.Manual = QtWidgets.QWidget()
        self.Manual.setObjectName("Manual")
        self.ManualEntryUpdateButton = QtWidgets.QPushButton(self.Manual)
        self.ManualEntryUpdateButton.setGeometry(QtCore.QRect(230, 52, 121, 111))
        self.ManualEntryUpdateButton.setObjectName("ManualEntryUpdateButton")
        self.ManualAngleEntryButton = QtWidgets.QPushButton(self.Manual)
        self.ManualAngleEntryButton.setGeometry(QtCore.QRect(540, 50, 121, 111))
        self.ManualAngleEntryButton.setObjectName("ManualAngleEntryButton")
        self.sliderButton = QtWidgets.QPushButton(self.Manual)
        self.sliderButton.setGeometry(QtCore.QRect(230, 280, 75, 23))
        self.sliderButton.setObjectName("sliderButton")
        self.panServoSlider = QtWidgets.QSlider(self.Manual)
        self.panServoSlider.setGeometry(QtCore.QRect(200, 340, 160, 22))
        self.panServoSlider.setOrientation(QtCore.Qt.Horizontal)
        self.panServoSlider.setObjectName("panServoSlider")
        self.tiltServoSlider = QtWidgets.QSlider(self.Manual)
        self.tiltServoSlider.setGeometry(QtCore.QRect(200, 390, 160, 22))
        self.tiltServoSlider.setOrientation(QtCore.Qt.Horizontal)
        self.tiltServoSlider.setObjectName("tiltServoSlider")
        self.trimUpButton = QtWidgets.QPushButton(self.Manual)
        self.trimUpButton.setGeometry(QtCore.QRect(540, 290, 75, 23))
        self.trimUpButton.setObjectName("trimUpButton")
        self.trimLeftButton = QtWidgets.QPushButton(self.Manual)
        self.trimLeftButton.setGeometry(QtCore.QRect(470, 380, 75, 23))
        self.trimLeftButton.setObjectName("trimLeftButton")
        self.trimDownButton = QtWidgets.QPushButton(self.Manual)
        self.trimDownButton.setGeometry(QtCore.QRect(560, 380, 75, 23))
        self.trimDownButton.setObjectName("trimDownButton")
        self.trimRightButton = QtWidgets.QPushButton(self.Manual)
        self.trimRightButton.setGeometry(QtCore.QRect(660, 380, 75, 23))
        self.trimRightButton.setObjectName("trimRightButton")
        self.trimResetButton = QtWidgets.QPushButton(self.Manual)
        self.trimResetButton.setGeometry(QtCore.QRect(660, 300, 75, 23))
        self.trimResetButton.setObjectName("trimResetButton")
        self.tabs.addTab(self.Manual, "")
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusLabel.setGeometry(QtCore.QRect(510, 610, 191, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.statusLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(24)
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.statusLabel.setFont(font)
        self.statusLabel.setObjectName("statusLabel")
        self.status = QtWidgets.QLabel(self.centralwidget)
        self.status.setGeometry(QtCore.QRect(830, 610, 191, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(243, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.status.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(24)
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.status.setFont(font)
        self.status.setObjectName("status")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1300, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.incomingData, self.groundData)
        MainWindow.setTabOrder(self.groundData, self.tabs)
        MainWindow.setTabOrder(self.tabs, self.getLocal)
        MainWindow.setTabOrder(self.getLocal, self.bearingNorth)
        MainWindow.setTabOrder(self.bearingNorth, self.bearingEast)
        MainWindow.setTabOrder(self.bearingEast, self.bearingSouth)
        MainWindow.setTabOrder(self.bearingSouth, self.bearingWest)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.incomingLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Incoming GPS Data:", None, -1))
        self.incomingData.verticalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "Last Received Time", None, -1))
        self.incomingData.verticalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "Latitude", None, -1))
        self.incomingData.verticalHeaderItem(2).setText(QtWidgets.QApplication.translate("MainWindow", "Longitude", None, -1))
        self.incomingData.verticalHeaderItem(3).setText(QtWidgets.QApplication.translate("MainWindow", "Altitude", None, -1))
        self.incomingData.verticalHeaderItem(4).setText(QtWidgets.QApplication.translate("MainWindow", "Elevation Angle", None, -1))
        self.incomingData.verticalHeaderItem(5).setText(QtWidgets.QApplication.translate("MainWindow", "Bearing (From North)", None, -1))
        self.incomingData.verticalHeaderItem(6).setText(QtWidgets.QApplication.translate("MainWindow", "Line-of-Sight (km)", None, -1))
        self.incomingData.verticalHeaderItem(7).setText(QtWidgets.QApplication.translate("MainWindow", "Mag Declination", None, -1))
        self.incomingData.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "Value", None, -1))
        self.groundData.verticalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "Latitude", None, -1))
        self.groundData.verticalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "Longitude", None, -1))
        self.groundData.verticalHeaderItem(2).setText(QtWidgets.QApplication.translate("MainWindow", "Altitude", None, -1))
        self.groundData.verticalHeaderItem(3).setText(QtWidgets.QApplication.translate("MainWindow", "Center Bearing (N)", None, -1))
        self.groundData.verticalHeaderItem(4).setText(QtWidgets.QApplication.translate("MainWindow", "Applied Bearing Offset", None, -1))
        self.groundData.verticalHeaderItem(5).setText(QtWidgets.QApplication.translate("MainWindow", "Applied Tilt Offset", None, -1))
        self.groundData.verticalHeaderItem(6).setText(QtWidgets.QApplication.translate("MainWindow", "Bearing Position", None, -1))
        self.groundData.verticalHeaderItem(7).setText(QtWidgets.QApplication.translate("MainWindow", "Elevation Position", None, -1))
        self.groundData.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "Value", None, -1))
        self.groundLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Ground Station Data:", None, -1))
        self.getLocal.setText(QtWidgets.QApplication.translate("MainWindow", "Get Local (Arduino)", None, -1))
        self.bearingSouth.setText(QtWidgets.QApplication.translate("MainWindow", "South Facing", None, -1))
        self.bearingEast.setText(QtWidgets.QApplication.translate("MainWindow", "East Facing", None, -1))
        self.bearingWest.setText(QtWidgets.QApplication.translate("MainWindow", "West Facing", None, -1))
        self.bearingNorth.setText(QtWidgets.QApplication.translate("MainWindow", "North Facing", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Center Bearing (True):", None, -1))
        self.manualAlt.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "4934", None, -1))
        self.manualAltLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Altitude (ft):", None, -1))
        self.manualLon.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "-111.0445833", None, -1))
        self.manualLonLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Longitude (°):", None, -1))
        self.manualLat.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "45.6629505", None, -1))
        self.manualLatLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Latitude (°):", None, -1))
        self.manualSettingsEntryLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Manual Settings Entry:", None, -1))
        self.autoHybrid.setText(QtWidgets.QApplication.translate("MainWindow", "Hybrid (RFD900 + Iridium)", None, -1))
        self.autoDisabled.setText(QtWidgets.QApplication.translate("MainWindow", "Disabled", None, -1))
        self.autoRFD.setText(QtWidgets.QApplication.translate("MainWindow", "RFD900", None, -1))
        self.autoIridium.setText(QtWidgets.QApplication.translate("MainWindow", "Iridium", None, -1))
        self.autoIridiumPredict.setText(QtWidgets.QApplication.translate("MainWindow", "Iridium + Prediction", None, -1))
        self.autoSimulation.setText(QtWidgets.QApplication.translate("MainWindow", "Simulation", None, -1))
        self.autotrackLabel.setText(QtWidgets.QApplication.translate("MainWindow", "AutoTrack:", None, -1))
        self.simulationFlightLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Simulation Flight:", None, -1))
        self.simDateLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Date (yyyy-mm-dd):", None, -1))
        self.simDate.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "2015-04-10", None, -1))
        self.simAltLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Simulation Start Alt (meters):", None, -1))
        self.simAlt.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "1000", None, -1))
        self.pointLong.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "-111.0445833", None, -1))
        self.pointLat.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "45.6629505", None, -1))
        self.pointtolatitudelabel.setText(QtWidgets.QApplication.translate("MainWindow", "Point-To Latitude (°):", None, -1))
        self.pointtolongitudelabel.setText(QtWidgets.QApplication.translate("MainWindow", "Point-To Longitude (°):", None, -1))
        self.pointAlt.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "5000", None, -1))
        self.pointtoaltitudelabel.setText(QtWidgets.QApplication.translate("MainWindow", "Point-To Altitude(ft):", None, -1))
        self.simulationFlightLabel_2.setText(QtWidgets.QApplication.translate("MainWindow", "Point-To Coordinates:", None, -1))
        self.PointButton.setText(QtWidgets.QApplication.translate("MainWindow", "Point-To", None, -1))
        self.updateSettings.setText(QtWidgets.QApplication.translate("MainWindow", "Update Settings", None, -1))
        self.antennaCenter.setText(QtWidgets.QApplication.translate("MainWindow", "Move Antennas to Center", None, -1))
        self.trackerLaunch.setText(QtWidgets.QApplication.translate("MainWindow", "Launch Antenna Tracker", None, -1))
        self.pointAtBalloon.setText(QtWidgets.QApplication.translate("MainWindow", "Point at Most Recent Balloon Location", None, -1))
        self.recalibrateCenterBearing.setText(QtWidgets.QApplication.translate("MainWindow", "Recalibrate Center Bearing", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("MainWindow", "Connections:", None, -1))
        self.arduinoAttached.setText(QtWidgets.QApplication.translate("MainWindow", "Arduino Connected", None, -1))
        self.servoAttached.setText(QtWidgets.QApplication.translate("MainWindow", "Servos Connected", None, -1))
        self.servoCOM.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "COM8", None, -1))
        self.rfdAttached.setText(QtWidgets.QApplication.translate("MainWindow", "RFD Connected", None, -1))
        self.arduinoCOM.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "COM7", None, -1))
        self.rfdCOM.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "COM24", None, -1))
        self.calibrationGoalVal.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "8", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "      Calibration Goal", None, -1))
        self.simDateLabel_3.setText(QtWidgets.QApplication.translate("MainWindow", "COM Port:", None, -1))
        self.checkComPorts.setText(QtWidgets.QApplication.translate("MainWindow", "SEARCH MY ", None, -1))
        self.tabs.setTabText(self.tabs.indexOf(self.Settings), QtWidgets.QApplication.translate("MainWindow", "Settings", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Antenna", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Adjust", None, -1))
        self.tabs.setTabText(self.tabs.indexOf(self.Tracker), QtWidgets.QApplication.translate("MainWindow", "Tracker", None, -1))
        self.cutdownButton.setText(QtWidgets.QApplication.translate("MainWindow", "Send Cutdown", None, -1))
        self.idleButton.setText(QtWidgets.QApplication.translate("MainWindow", "IDLE", None, -1))
        self.tabs.setTabText(self.tabs.indexOf(self.Commands), QtWidgets.QApplication.translate("MainWindow", "Commands", None, -1))
        self.ManualEntryUpdateButton.setText(QtWidgets.QApplication.translate("MainWindow", "Manual Entry Update", None, -1))
        self.ManualAngleEntryButton.setText(QtWidgets.QApplication.translate("MainWindow", "Manual Angle Update", None, -1))
        self.sliderButton.setText(QtWidgets.QApplication.translate("MainWindow", "Slider Start", None, -1))
        self.trimUpButton.setText(QtWidgets.QApplication.translate("MainWindow", "upp", None, -1))
        self.trimLeftButton.setText(QtWidgets.QApplication.translate("MainWindow", "L", None, -1))
        self.trimDownButton.setText(QtWidgets.QApplication.translate("MainWindow", "DD", None, -1))
        self.trimRightButton.setText(QtWidgets.QApplication.translate("MainWindow", "rite", None, -1))
        self.trimResetButton.setText(QtWidgets.QApplication.translate("MainWindow", "trim reset", None, -1))
        self.tabs.setTabText(self.tabs.indexOf(self.Manual), QtWidgets.QApplication.translate("MainWindow", "Manual Control", None, -1))
        self.statusLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Autotrack: ", None, -1))
        self.status.setText(QtWidgets.QApplication.translate("MainWindow", "Offline", None, -1))

